@URL=http://localhost:8080/dispositivo

### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "teste1",
    "descricao": "teste11",
    "localizacao": "11,11",
    "gatewayid": 1
    
}

### Obter todas as pessoas
GET {{URL}}

### Obter um gateway
GET {{URL}}/2

### Atualizar um gateway
PUT {{URL}}/1
Content-Type: application/json

{
    "nome": "Anas",
    "descricao": "reste",
    "localizacao": "2,2",
    "gatewayid": "2"
}

### Deletar uma pessoa
DELETE {{URL}}/2