@URL=http://localhost:8080/gateway

### CREATE
POST {{URL}}
Content-Type: application/json

{
    "nome": "tessste",
    "descricao": "tesste1",
    "pessoaid": 1
    
}

### Obter todas as pessoas
GET {{URL}}

### Obter um gateway
GET {{URL}}/2

### Atualizar um gateway
PUT {{URL}}/1
Content-Type: application/json

{
    "nome": "Anas",
    "descricao": "reste",
    "pessoaid": 2
}

### Deletar uma pessoa
DELETE {{URL}}/2